# -*- coding: utf-8 -*-
import os
B=r"d:\APP\Python 3.13\挑战杯\data\knowledge_sources\c919\04_terms_graph"
M=[]
def A(s):return"["+", ".join(f'"{i}"'for i in s.split(","))+"]"
def gt(f,s,t,c,p,e):
 L=[f"# {t}",f"# {c}",f"# ID 前缀：{p}","","terms:"]
 for i,(n,a,y,d) in enumerate(e,1):L+=[f'  - term_id: "{p}{i:03d}"',f'    canonical_name: "{n}"',f'    aliases: {A(a)}',f'    node_type: "{y}"',f'    definition: "{d}"',f'    source_ref: "{s}"',""]
 open(os.path.join(B,"terms",f),"w",encoding="utf-8").write("\n".join(L));M.append((s,f"terms/{f}",len(e),"term_count",t,c))
def ge(f,s,t,c,p,e):
 L=[f"# {t}",f"# {c}",f"# node_id 前缀：{p}","","entities:"]
 for nid,nt,n,a,d,sp in e:
  L+=[f'  - node_id: "{nid}"',f'    node_type: "{nt}"',f'    canonical_name: "{n}"',f'    aliases: {A(a)}',f'    description: "{d}"']
  if sp:L+=[f'    specifications:']+[f'      {k}: {v}' for k,v in sp]
  L+=[f'    applicable_aircraft: ["c919"]',""]
 open(os.path.join(B,"entities",f),"w",encoding="utf-8").write("\n".join(L));M.append((s,f"entities/{f}",len(e),"entity_count",t,c))
def gr(f,s,t,c,p,e):
 L=[f"# {t}",f"# {c}",f"# edge_id 前缀：{p}","","relations:"]
 for eid,sn,tn,rt,cf,d in e:L+=[f'  - edge_id: "{eid}"',f'    source_node_id: "{sn}"',f'    target_node_id: "{tn}"',f'    relation_type: "{rt}"',f'    confidence: {cf}',f'    description: "{d}"',""]
 open(os.path.join(B,"relations",f),"w",encoding="utf-8").write("\n".join(L));M.append((s,f"relations/{f}",len(e),"relation_count",t,c))
# === TERMS DATA ===
gt("terms-aerodynamics-lift-20260728-candidate.yaml","c919-graph-aero-lift-v1","C919 升力类气动术语","按升力原理拆分的气动术语","aerlft_",[
("升力","升力,lift,L","concept","垂直于来流方向、克服飞机重力的气动力，由机翼上下表面压差产生"),
("升力系数","升力系数,CL,lift coefficient","concept","无量纲化升力表达 CL=L/(0.5ρV²S)，与迎角和翼型几何相关"),
("迎角","迎角,攻角,angle of attack,AoA","concept","机翼弦线与来流方向的夹角，C919 巡航迎角约 2°-4°"),
("失速","失速,stall,气流分离","concept","迎角超过临界值后气流分离升力急剧下降，C919 飞控具备失速保护"),
("抖振","抖振,buffet,抖振边界","concept","气流分离产生的非定常气动激励导致机翼或尾翼振荡"),
("临界迎角","临界迎角,critical AoA,stall angle","concept","升力系数达最大值对应的迎角，超临界翼型约 16°-18°"),
("升阻比","升阻比,L/D,气动效率","concept","升力与阻力之比，C919 巡航升阻比约 18-20"),
("升力斜线","升力斜线,升力曲线斜率,lift curve slope","concept","升力系数随迎角变化的线性段斜率 dCL/dα"),
("涡量","涡量,vorticity","concept","流体微元旋转角速度的两倍，描述旋涡强度的物理量"),
("环量","环量,circulation","concept","速度沿闭合曲线的线积分，关联升力与环量"),
("压力中心","压力中心,center of pressure,CP","concept","气动合力作用点，位置随迎角变化"),
("气动中心","气动中心,aerodynamic center,AC","concept","俯仰力矩不随迎角变化的固定点，约在 1/4 弦长位置"),
])
gt("terms-aerodynamics-drag-20260728-candidate.yaml","c919-graph-aero-drag-v1","C919 阻力类气动术语","按阻力来源拆分的气动术语","aerdrg_",[
("阻力","阻力,drag,D","concept","平行来流方向阻碍飞机前进的气动力，分诱导阻力和寄生阻力"),
("诱导阻力","诱导阻力,induced drag","concept","机翼产生升力时翼尖涡流导致的阻力，与升力系数平方成正比"),
("寄生阻力","寄生阻力,parasite drag,废阻力","concept","与升力无关的气动阻力，含摩擦、压差和干扰阻力"),
("激波阻力","激波阻力,波阻,wave drag","concept","跨声速飞行时激波形成导致的阻力增加"),
("摩擦阻力","摩擦阻力,skin friction drag","concept","空气流过飞机表面粘性剪切应力产生的阻力，约占巡航总阻力 45%-50%"),
("压差阻力","压差阻力,pressure drag,形状阻力","concept","物体前后压力差形成的阻力，与外形流线度相关"),
("干扰阻力","干扰阻力,interference drag","concept","部件连接处气流相互干扰产生的额外阻力"),
("阻力发散","阻力发散,drag divergence","concept","马赫数超临界值后阻力系数急剧上升，C919 约在 M0.85"),
("阻力系数","阻力系数,CD,drag coefficient","concept","无量纲化阻力表达 CD=D/(0.5ρV²S)，巡航典型 0.025-0.035"),
("减阻","减阻,drag reduction","concept","通过外形优化、翼尖小翼等手段降低阻力，C919 小翼减阻约 3%-5%"),
("层流","层流,laminar flow","concept","流体分层有序流动无横向混合的状态，摩擦阻力低于湍流"),
("湍流","湍流,turbulent flow","concept","流体不规则脉动混合的流动状态，抗分离能力更强"),
])
gt("terms-aerodynamics-wing-20260728-candidate.yaml","c919-graph-aero-wing-v1","C919 机翼气动术语","按机翼气动设计拆分的术语","aerwg_",[
("超临界翼型","超临界翼型,supercritical airfoil","concept","上表面平坦下表面反曲的跨声速翼型，C919 采用第四代超临界翼型"),
("后掠角","后掠角,sweep angle","concept","机翼参考线与垂直机身对称面方向的夹角，C919 约 25°"),
("展弦比","展弦比,aspect ratio,AR","concept","翼展平方与机翼面积之比，C919 约 9.5，高展弦比降诱导阻力"),
("梢根比","梢根比,taper ratio","concept","翼尖弦长与翼根弦长之比，影响升力展向分布"),
("安装角","安装角,incidence angle","concept","机翼弦线与机身参考线的夹角，C919 约 3°"),
("扭转","扭转,washout,几何扭转","concept","沿展向改变翼型安装角，使翼根先于翼尖失速"),
("襟翼","襟翼,flap,后缘襟翼","concept","机翼后缘可偏转增升装置，C919 采用富勒式后缘襟翼"),
("缝翼","缝翼,slat,前缘缝翼","concept","机翼前缘可伸出增升装置，延缓大迎角失速"),
("副翼","副翼,aileron","concept","机翼后缘外侧可动翼面，差动偏转实现滚转操纵"),
("扰流板","扰流板,spoiler,减速板","concept","机翼上表面可偏转板面，空中减速辅助滚转地面破坏升力"),
("翼尖小翼","翼尖小翼,winglet,翼梢小翼","concept","安装在翼尖的倾斜翼面减弱翼尖涡流，C919 翼展含小翼 35.8m"),
("翼根","翼根,wing root","concept","机翼与机身连接处剖面，承受最大弯矩和剪力"),
])
gt("terms-aerodynamics-highspeed-20260728-candidate.yaml","c919-graph-aero-highspeed-v1","C919 高速气动术语","按高速气动现象拆分的术语","aerhs_",[
("马赫数","马赫数,Mach number,M","concept","流速与当地声速之比，C919 巡航马赫数 0.785"),
("临界马赫数","临界马赫数,critical Mach number","concept","翼面局部流速首次达声速的来流马赫数，C919 约 0.82"),
("阻力发散马赫数","阻力发散马赫数,drag divergence Mach","concept","阻力系数急剧上升的来流马赫数，C919 约 0.85"),
("声速","声速,speed of sound,a","concept","压力扰动传播速度，海平面标准大气约 340 m/s"),
("亚声速","亚声速,subsonic","concept","来流马赫数小于临界马赫数，全流场无激波"),
("跨声速","跨声速,transonic","concept","来流马赫数 0.8-1.2 附近，翼面同时存在亚超声速区域"),
("超声速","超声速,supersonic","concept","来流马赫数大于 1，产生弓形激波，C919 不在此范围"),
("激波","激波,shock wave","concept","超声速气流减速形成的强压缩不连续面，产生波阻"),
("膨胀波","膨胀波,expansion wave","concept","超声速气流绕外拐角加速形成的扇形稀疏波"),
("普朗特-格劳厄脱法则","普朗特-格劳厄脱法则,Prandtl-Glauert rule","concept","亚声速压缩性修正关系 CL=CL不可压/sqrt(1-M²)"),
("面积律","面积律,area rule","concept","跨声速时沿机身纵截面面积分布平滑可减小波阻的设计原理"),
("压缩性","压缩性,compressibility","concept","高速飞行时空气密度随压力变化不可忽略的效应"),
])
gt("terms-aerodynamics-stability-20260728-candidate.yaml","c919-graph-aero-stability-v1","C919 稳定性与操纵术语","按稳定性类型拆分的术语","aerstb_",[
("纵向稳定性","纵向稳定性,longitudinal stability","concept","飞机保持或恢复纵向平衡的能力，由平尾和重心-焦点位置决定"),
("横向稳定性","横向稳定性,lateral stability","concept","飞机保持或恢复滚转平衡的能力，由上反角和后掠角提供"),
("航向稳定性","航向稳定性,directional stability","concept","飞机保持或恢复航向平衡的能力，由垂直尾翼提供"),
("静稳定","静稳定,static stability","concept","受扰后初始恢复力矩使其回原平衡状态的特性"),
("动稳定","动稳定,dynamic stability","concept","受扰后运动随时间收敛回平衡状态的特性"),
("阻尼","阻尼,damping","concept","运动中耗散能量使振幅衰减的作用，C919 飞控提供人工阻尼"),
("俯仰","俯仰,pitch","concept","绕飞机横轴的旋转运动，由升降舵控制"),
("滚转","滚转,roll","concept","绕飞机纵轴的旋转运动，由副翼差动控制"),
("偏航","偏航,yaw","concept","绕飞机竖轴的旋转运动，由方向舵控制"),
("重心","重心,center of gravity,CG","concept","飞机全部质量的等效作用点，须在允许范围内"),
("焦点","焦点,neutral point","concept","俯仰力矩不随迎角变化的对焦点，重心在焦点前则静稳定"),
("操纵余量","操纵余量,static margin","concept","重心到焦点距离占平均气动弦长百分比，C919 典型 5%-15%"),
])
# === TERMS DATA PART 2 ===
gt("terms-structures-fuselage-20260728-candidate.yaml","c919-graph-struct-fuselage-v1","C919 机身结构术语","按机身结构拆分的术语","strfus_",[
("机身","机身,fuselage,机体","component","C919 主体结构，机身宽度 3.96m 高度 4.166m 横截面积 12.915m²"),
("前机身","前机身,forward fuselage","component","机身前段含驾驶舱雷达罩和前起落架舱"),
("中机身","中机身,mid fuselage","component","机身中段连接中央翼盒承载主客舱和主起落架舱"),
("后机身","后机身,aft fuselage","component","机身后段含 APU 舱尾椎和水平尾翼安装接口"),
("气密舱","气密舱,pressure cabin,增压舱","component","机身内部可增压密封区域维持高空座舱压力"),
("框","框,frame,隔框","component","机身横截面环形承力骨架维持截面形状传递径向载荷"),
("桁条","桁条,stringer","component","机身纵向骨架构件传递轴向载荷支持蒙皮"),
("蒙皮","蒙皮,skin","component","机身外表面薄壁结构承受增压剪切载荷，C919 采用铝锂合金"),
("长桁","长桁,longeron","component","机身截面较强的大梁纵向构件承受弯曲主要轴向力"),
("地板梁","地板梁,floor beam","component","支撑客舱地板的横向梁结构连接机身两侧桁条"),
("客舱","客舱,cabin","component","机身内旅客乘坐增压舱段，C919 典型 3-3 布局 158-192 座"),
("货舱","货舱,cargo hold","component","机身下部行李货物运输舱段位于客舱地板下方"),
])
gt("terms-structures-wing-20260728-candidate.yaml","c919-graph-struct-wing-v1","C919 机翼结构术语","按机翼结构拆分的术语","strwg_",[
("翼盒","翼盒,wing box,扭力盒","component","机翼主要承力盒形结构由翼梁翼肋和蒙皮组成承受弯剪扭"),
("翼梁","翼梁,spar","component","机翼展向主承力构件承受弯曲剪力分前梁和后梁"),
("翼肋","翼肋,rib","component","机翼弦向构件维持翼型形状将载荷传递给翼梁"),
("桁条","桁条,stringer","component","机翼展向纵向构件支持蒙皮承受压缩载荷"),
("蒙皮","蒙皮,skin,机翼蒙皮","component","机翼上下表面薄壁结构承受扭转和部分弯曲载荷"),
("中央翼盒","中央翼盒,center wing box","component","贯穿机身中部的机翼承力核心同时作为中央油箱"),
("外翼盒","外翼盒,outer wing box","component","中央翼盒以外至翼尖的机翼盒段承受飞行气动载荷"),
("前梁","前梁,front spar","component","翼盒前部展向主梁承受主要剪力定义机翼前缘结构"),
("后梁","后梁,rear spar","component","翼盒后部展向主梁为襟翼副翼提供安装接口"),
("翼根","翼根,wing root","component","机翼与机身连接区域承受最大弯矩和剪力"),
("翼尖","翼尖,wing tip","component","机翼最外侧端部安装翼尖小翼需考虑颤振"),
("翼根接头","翼根接头,wing root joint","component","机翼与机身或中央翼盒的机械连接结构"),
])
gt("terms-structures-empennage-20260728-candidate.yaml","c919-graph-struct-empennage-v1","C919 尾翼结构术语","按尾翼结构拆分的术语","stremp_",[
("垂直尾翼","垂直尾翼,vertical tail,垂尾","component","尾翼垂直翼面提供航向稳定性后缘安装方向舵"),
("水平尾翼","水平尾翼,horizontal tail,平尾","component","尾翼水平翼面提供纵向稳定性C919 采用低平尾布局"),
("方向舵","方向舵,rudder","component","垂直尾翼后缘可动翼面控制偏航运动"),
("升降舵","升降舵,elevator","component","水平尾翼后缘可动翼面控制俯仰运动"),
("安定面","安定面,stabilizer","component","尾翼中固定翼面部分提供稳定性基线"),
("配平片","配平片,trim tab","component","舵面后缘可调小翼面减小或消除操纵杆力"),
("腹鳍","腹鳍,ventral fin","component","机身尾部下方垂直翼面增强航向稳定性"),
("背鳍","背鳍,dorsal fin","component","机身尾部至垂尾根部整流翼面改善气流"),
("翼根","翼根,tail root","component","尾翼与机身连接区域承受尾翼弯矩和剪力"),
("翼尖","翼尖,tail tip","component","尾翼最外侧端部需考虑颤振和重量优化"),
("后掠角","后掠角,tail sweep","concept","尾翼参考线与垂直方向夹角C919 平尾垂尾均有后掠角"),
("安装角","安装角,tail incidence","concept","尾翼弦线与机身参考线夹角水平安定面通常可调"),
])
gt("terms-structures-landing-gear-20260728-candidate.yaml","c919-graph-struct-lg-v1","C919 起落架结构术语","按起落架结构拆分的术语","strlg_",[
("前起落架","前起落架,nose landing gear,NLG","component","前机身下方可收放起落架双轮式提供地面转向操纵"),
("主起落架","主起落架,main landing gear,MLG","component","机身中部下方可收放起落架左右各一套四轮式"),
("机轮","机轮,wheel","component","起落架接地滚动部件C919 共六主轮加两前轮"),
("刹车","刹车,brake","component","机轮内多盘式碳-钢刹车组件C919 采用碳刹车"),
("轮胎","轮胎,tire","component","机轮外圈充气橡胶轮胎"),
("减震支柱","减震支柱,shock strut","component","起落架主缓冲结构通过油气压缩吸收着陆冲击"),
("收放机构","收放机构,retraction mechanism","component","起落架液压驱动的收放装置"),
("转弯机构","转弯机构,steering mechanism","component","前起落架液压转弯系统提供地面转向控制"),
("舱门","舱门,gear door","component","覆盖起落架舱开口的结构门收起后关闭保持气动外形"),
("支柱","支柱,strut","component","起落架主要承力柱状结构传递垂直载荷"),
("摇臂","摇臂,rocker arm","component","连接起落架内外筒的连杆传递扭矩"),
("扭力臂","扭力臂,torque link","component","起落架缓冲支柱上下段连杆防止活塞旋转"),
])
gt("terms-structures-load-20260728-candidate.yaml","c919-graph-struct-load-v1","C919 载荷与强度术语","按载荷类型拆分的术语","strld_",[
("极限载荷","极限载荷,ultimate load","concept","结构设计必须承受的最大载荷等于限制载荷乘安全系数 1.5"),
("限制载荷","限制载荷,limit load","concept","服役期内预期最大载荷结构在此载荷下不应永久变形"),
("安全系数","安全系数,factor of safety","concept","极限载荷与限制载荷之比航空结构通常取 1.5"),
("疲劳","疲劳,fatigue","concept","反复交变载荷下材料产生裂纹并扩展的现象"),
("疲劳寿命","疲劳寿命,fatigue life","concept","结构至疲劳断裂的循环次数C919 设计目标 90000 飞行小时"),
("损伤容限","损伤容限,damage tolerance","concept","结构含裂纹状态下仍能在检修周期内安全承载的设计理念"),
("裂纹","裂纹,crack","concept","材料在疲劳或应力腐蚀下产生的扩展型缺陷"),
("应力","应力,stress","concept","单位面积上的内力结构设计须控制应力在许用值内"),
("应变","应变,strain","concept","单位长度变形量弹性范围内应力与应变成正比"),
("屈服","屈服,yield","concept","材料开始产生永久变形的应力水平"),
("断裂","断裂,fracture","concept","材料在应力作用下完全分离破坏的现象"),
("许用应力","许用应力,allowable stress","concept","结构设计中允许使用的最大应力值"),
])
gt("terms-systems-flight-control-20260728-candidate.yaml","c919-graph-sys-fc-v1","C919 飞控系统术语","按飞控功能拆分的术语","sysfc_",[
("电传操纵","电传操纵,fly-by-wire,FBW","concept","以电信号替代机械连杆传递操纵指令C919 采用全权限电传飞控"),
("控制律","控制律,control law","concept","飞控计算机中定义操纵指令与舵面偏转关系的算法"),
("正常模式","正常模式,normal mode","concept","飞控全功能工作模式提供完整包线保护和增稳"),
("备用模式","备用模式,alternate mode","concept","降级飞控模式部分传感器或余度通道失效时启用"),
("直接模式","直接模式,direct mode","concept","最低飞控模式飞行员指令直接映射到舵面无增稳"),
("包线保护","包线保护,envelope protection","concept","飞控自动限制飞行参数不超出安全边界"),
("俯仰保护","俯仰保护,pitch protection","concept","防止俯仰角或法向过载超出安全范围"),
("坡度保护","坡度保护,bank protection","concept","防止坡度角超出安全范围正常模式限制约 67°"),
("失速保护","失速保护,stall protection","concept","接近失速迎角时自动推杆降低迎角"),
("超速保护","超速保护,overspeed protection","concept","接近最大使用马赫数或速度时自动拉杆减速"),
("余度","余度,redundancy","concept","多重通道备份提高可靠性C919 飞控三余度或四余度"),
("作动器","作动器,actuator","concept","将液压或电力转换为机械运动驱动舵面的执行元件"),
])
gt("terms-systems-hydraulic-20260728-candidate.yaml","c919-graph-sys-hyd-v1","C919 液压系统术语","按液压元件拆分的术语","syshyd_",[
("液压泵","液压泵,hydraulic pump","concept","将机械能转换为液压能的动力元件"),
("EDP","EDP,engine driven pump,发动机驱动泵","concept","由发动机附件齿轮箱驱动的液压泵主供压源"),
("EMP","EMP,electric motor pump,电动泵","concept","电动机驱动的液压泵提供备份和地面液压动力"),
("蓄压器","蓄压器,accumulator","concept","储存液压油和气体的压力容器提供峰值流量补充"),
("油箱","油箱,hydraulic reservoir","concept","储存液压油的容器提供系统供油和回油容纳空间"),
("压力","压力,hydraulic pressure","concept","液压系统工作压力C919 为 3000 psi 约 20.7 MPa"),
("3000psi","3000psi,3000 psi","concept","C919 液压系统额定工作压力"),
("作动器","作动器,hydraulic actuator","concept","将液压能转换为直线或旋转运动的执行元件"),
("伺服阀","伺服阀,servo valve","concept","将电信号转换为液压流量控制的精密阀门"),
("换向阀","换向阀,directional valve","concept","控制液压油流向的开关阀"),
("溢流阀","溢流阀,relief valve","concept","液压系统过压时自动开启泄油的安全保护阀"),
("液压油","液压油,hydraulic fluid,Skydrol","concept","传递压力的工作介质C919 采用磷酸酯抗燃液压油"),
])
gt("terms-systems-fuel-20260728-candidate.yaml","c919-graph-sys-fuel-v1","C919 燃油系统术语","按燃油功能拆分的术语","sysfuel_",[
("油箱","油箱,fuel tank","concept","储存燃油的密封容器C919 含中央油箱和左右机翼油箱"),
("中央油箱","中央油箱,center tank","concept","位于中央翼盒内的油箱C919 容量约 7600 升"),
("机翼油箱","机翼油箱,wing tank","concept","位于左右机翼盒段内的油箱每侧约 5780 升"),
("通气","通气,ventilation","concept","油箱与外界大气连通的系统维持压力平衡"),
("加油","加油,refueling","concept","向油箱注入燃油的操作C919 采用压力加油"),
("抽油","抽油,defueling","concept","从油箱抽出燃油的操作用于维修或紧急减重"),
("输油","输油,fuel transfer","concept","油箱之间转输燃油以控制重心和平衡"),
("油泵","油泵,fuel pump","concept","提供燃油输送压力的动力元件"),
("油量测量","油量测量,fuel quantity measurement","concept","通过电容式传感器测量油箱内燃油体积"),
("惰性气体","惰性气体,inert gas,OBIGGS","concept","向油箱充入富氮气体降低氧气浓度防止可燃"),
("燃油","燃油,fuel","concept","飞机发动机使用的液体燃料C919 使用 Jet A-1"),
("航空煤油","航空煤油,Jet A-1","concept","航空燃气涡轮发动机标准燃料闪点约 38°C 冰点-47°C"),
])
gt("terms-systems-electrical-20260728-candidate.yaml","c919-graph-sys-elec-v1","C919 电气系统术语","按电气功能拆分的术语","syselec_",[
("发电机","发电机,generator","concept","将发动机机械能转换为电能的设备"),
("IDG","IDG,integrated drive generator","concept","发动机驱动恒速恒频发电机输出 115V AC 400Hz"),
("变压整流器","变压整流器,TRU","concept","将 115V AC 转换为 28V DC 的电力变换设备"),
("汇流条","汇流条,bus,busbar","concept","电气系统中分配电力的公共母线节点"),
("270VDC","270VDC,270V DC","concept","C919 部分系统采用 270V 高压直流配电"),
("蓄电池","蓄电池,battery,电瓶","concept","储存电能的化学电池组C919 主蓄电池为镍镉电池"),
("RAT","RAT,ram air turbine","concept","应急时弹出的风力涡轮发电机提供应急电力和液压"),
("EPU","EPU,emergency power unit","concept","辅助应急动力装置提供有限电力和液压"),
("配电","配电,power distribution","concept","将发电系统电力按需求分配到用电设备的管理系统"),
("断路器","断路器,circuit breaker,CB","concept","过流或短路时自动断开电路的保护装置"),
("逆变器","逆变器,inverter","concept","将直流电转换为交流电的电力变换设备"),
("接地","接地,grounding","concept","将电气设备外壳或回路连接到飞机结构参考零电位点"),
])
gt("terms-systems-ecs-20260728-candidate.yaml","c919-graph-sys-ecs-v1","C919 环控系统术语","按环控功能拆分的术语","sysecs_",[
("引气","引气,bleed air","concept","从发动机压气机提取的高温压缩空气为环控防冰增压提供气源"),
("座舱增压","座舱增压,cabin pressurization","concept","向客舱输送压缩空气并调节排气维持高于外部的座舱压力"),
("座舱高度","座舱高度,cabin altitude","concept","座舱内气压对应的海拔高度C919 巡航不超过 2400m"),
("空调组件","空调组件,air conditioning pack","concept","对引气进行制冷和调温的成套设备C919 配备两套"),
("空气循环机","空气循环机,air cycle machine,ACM","concept","利用布雷顿循环通过涡轮膨胀降温的制冷核心部件"),
("热交换器","热交换器,heat exchanger","concept","空调组件中冷热气流热交换的散热器"),
("水分离器","水分离器,water separator","concept","从冷气流中分离冷凝水分的装置防止管路结冰"),
("温度控制","温度控制,temperature control","concept","调节座舱送风温度的系统C919 客舱目标约 22-24°C"),
("压力调节","压力调节,pressure control","concept","通过调节排气阀开度控制座舱压力和变化率"),
("冲压空气","冲压空气,ram air","concept","利用飞行速度引入外界空气用于散热和应急通风"),
("OAT","OAT,outside air temperature","concept","飞机外部环境静温巡航高度约 -55°C"),
("过滤器","过滤器,filter,HEPA","concept","去除空气中颗粒和微生物的过滤元件C919 采用 HEPA"),
])
gt("terms-systems-avionics-20260728-candidate.yaml","c919-graph-sys-avn-v1","C919 航电系统术语","按航电功能拆分的术语","sysavn_",[
("IMA","IMA,综合模块化航电","concept","计算资源集中共享多功能在同一平台运行的航电架构"),
("ARINC 664","ARINC 664,AFDX","concept","基于以太网的航空数据总线标准C919 核心总线采用 AFDX"),
("ARINC 429","ARINC 429","concept","传统 32 位串行航空数据总线标准"),
("显示单元","显示单元,display unit,DU","concept","驾驶舱电子飞行显示器C919 采用 6 块 15.4 寸液晶"),
("FMS","FMS,flight management system","concept","集成导航性能优化和飞行计划管理的航电子系统"),
("飞行管理","飞行管理,flight management","concept","FMS 核心功能含飞行计划导航数据库性能计算和制导"),
("气象雷达","气象雷达,weather radar,WXR","concept","机载 X 波段雷达探测航路降水和风切变"),
("TCAS","TCAS,空中防撞系统","concept","独立监视附近飞机并发出避撞建议C919 配备 TCAS II"),
("EGPWS","EGPWS,近地警告系统","concept","增强型地形感知和近地警告系统C919 由 Honeywell 提供"),
("ADS-B","ADS-B,广播式自动相关监视","concept","飞机自动广播位置和状态信息的监视技术"),
("惯导","惯导,IRS,inertial reference system","concept","利用陀螺和加速度计测量姿态和位置的自主导航系统"),
("GPS","GPS,global positioning system","concept","卫星导航定位系统C919 配备多模式接收机 MMR"),
])
gt("terms-systems-ice-protection-20260728-candidate.yaml","c919-graph-sys-ice-v1","C919 防冰系统术语","按防冰方式拆分的术语","sysice_",[
("防冰","防冰,anti-icing","concept","防止冰在飞机表面形成的保护方式C919 机翼前缘采用热气防冰"),
("除冰","除冰,de-icing","concept","在冰已形成后周期性去除积冰的保护方式"),
("引气防冰","引气防冰,bleed air anti-ice","concept","利用发动机高温引气加热机翼前缘或发动机进气道"),
("电加热","电加热,electrical heating","concept","通过电阻丝通电发热加热部件表面的防冰方式"),
("气动除冰","气动除冰,pneumatic de-ice","concept","翼面安装可充气橡胶靴膨胀时破碎脱落积冰的除冰方式"),
("结冰","结冰,icing","concept","过冷水滴撞击飞机表面在低温下冻结形成冰层"),
("过冷水","过冷水,supercooled water","concept","温度低于冰点但仍保持液态的水滴撞击表面时立即结冰"),
("冰探测器","冰探测器,ice detector","concept","感知结冰条件的传感器C919 探测到结冰后自动启动防冰"),
("风挡加热","风挡加热,windshield heating","concept","通过电加热或热气加热保持驾驶舱风挡透明防冰"),
("皮托管加热","皮托管加热,pitot heat","concept","电加热皮托管入口防止结冰堵塞气压测量通道"),
("传感器加热","传感器加热,sensor heating","concept","电加热迎角传感器和总温探头防止结冰影响测量"),
("短舱防冰","短舱防冰,cowl anti-ice","concept","利用引气加热发动机进气道前缘防止结冰脱落损伤发动机"),
])
gt("terms-systems-fire-protection-20260728-candidate.yaml","c919-graph-sys-fire-v1","C919 防火系统术语","按防火功能拆分的术语","sysfire_",[
("火警探测器","火警探测器,fire detector","concept","感知高温或火焰并发出告警的传感器C919 采用环路式"),
("烟雾探测器","烟雾探测器,smoke detector","concept","探测货舱和卫生间空气中烟雾颗粒的传感器"),
("灭火瓶","灭火瓶,fire extinguisher bottle","concept","储存灭火剂并可在指令下释放的容器C919 发动机舱两套"),
("卤代烷","卤代烷,halon","concept","含卤素的灭火剂C919 采用 Halon 1301"),
("哈龙","哈龙,Halon,Halon 1301","concept","一溴三氟甲烷灭火剂灭火效率高航空仍广泛使用"),
("灭火器","灭火器,extinguisher","concept","手持或固定式灭火装置客舱配备便携式水灭火器和哈龙"),
("防火区","防火区,fire zone","concept","需要火警探测和灭火保护的区域C919 发动机APU货舱为防火区"),
("APU灭火","APU灭火,APU fire extinguishing","concept","APU 舱灭火系统可释放灭火剂并自动关闭 APU"),
("发动机灭火","发动机灭火,engine fire extinguishing","concept","发动机舱灭火系统每台发动机配备独立两套灭火瓶"),
("货舱灭火","货舱灭火,cargo fire extinguishing","concept","货舱火警探测和灭火系统"),
("警告系统","警告系统,warning system","concept","接收火警信号后在驾驶舱发出声光告警的系统"),
("手动灭火","手动灭火,manual extinguishing","concept","由飞行员手动操作释放灭火瓶的方式"),
])
gt("terms-systems-oxygen-20260728-candidate.yaml","c919-graph-sys-oxy-v1","C919 氧气系统术语","按供氧功能拆分的术语","sysoxy_",[
("氧气面罩","氧气面罩,oxygen mask","concept","旅客和机组使用的供氧面罩自动落下或手动取出"),
("化学氧发生器","化学氧发生器,chemical oxygen generator","concept","通过化学反应产生氧气的装置C919 旅客氧气由此提供"),
("氧气瓶","氧气瓶,oxygen cylinder","concept","储存高压氧气的容器C919 机组氧气由高压氧气瓶供给"),
("机组氧气","机组氧气,crew oxygen","concept","为驾驶舱飞行机组提供的持续供氧系统"),
("乘客氧气","乘客氧气,passenger oxygen","concept","为客舱旅客提供的应急供氧系统使用化学氧发生器"),
("供氧","供氧,oxygen supply","concept","向人员提供可呼吸氧气保证高空失压后生命安全"),
("14000ft","14000ft,14000 ft","concept","座舱高度超 14000ft 时旅客氧气面罩自动落下的触发阈值"),
("下降","下降,descent","concept","客舱失压后飞机紧急降低高度至安全氧气浓度的操作"),
("紧急下降","紧急下降,emergency descent","concept","失压后以最大允许下降率降至 10000ft 以下的紧急程序"),
("氧气持续时间","氧气持续时间,oxygen duration","concept","化学氧发生器可供氧的时间约 12-15 分钟"),
("供氧面罩","供氧面罩,supply mask","concept","机组快速佩戴式供氧面罩可在数秒内单手佩戴"),
("便携式氧气","便携式氧气,portable oxygen","concept","客舱中配备的手提式小氧气瓶供医疗急救或移动使用"),
])
gt("terms-systems-water-waste-20260728-candidate.yaml","c919-graph-sys-ww-v1","C919 水废水系统术语","按水废功能拆分的术语","sysww_",[
("淡水箱","淡水箱,potable water tank","concept","储存饮用水的容器C919 淡水箱容量约 200 升"),
("废水箱","废水箱,waste tank","concept","储存马桶排泄物的容器"),
("马桶","马桶,toilet","concept","客舱卫生间排泄物收集装置C919 采用真空抽吸式"),
("真空马桶","真空马桶,vacuum toilet","concept","利用客舱与外界压差抽吸冲洗的马桶系统"),
("冲洗","冲洗,flush","concept","马桶冲水操作真空系统利用压差抽吸"),
("供水","供水,water supply","concept","将淡水从水箱输送至厨房和卫生间的系统"),
("排水","排水,drain","concept","将废水和灰水排出机外的系统"),
("增压","增压,water pressurization","concept","利用引气或电动泵为水系统加压使水流出龙头"),
("加热","加热,water heating","concept","利用电加热器为厨房和卫生间提供热水"),
("水龙头","水龙头,faucet","concept","厨房和卫生间出水开关阀门"),
("洗手池","洗手池,wash basin","concept","卫生间洗手用盆灰水通过排水管排出机外"),
("污水","污水,wastewater,灰水","concept","厨房和洗手池产生的非排泄废水可直接排放机外"),
])
gt("terms-engine-turbofan-20260728-candidate.yaml","c919-graph-eng-tf-v1","C919 涡扇发动机术语","按涡扇原理拆分的术语","engtf_",[
("涡扇","涡扇,turbofan","concept","燃气涡轮发动机的一种外涵道风扇气流产生大部分推力"),
("内涵道","内涵道,core engine","concept","涡扇发动机核心部分气流经过压气机燃烧室和涡轮"),
("外涵道","外涵道,bypass duct","concept","风扇产生的不经过燃烧室的外部气流产生大部分推力"),
("涵道比","涵道比,bypass ratio,BPR","concept","外涵道空气质量流量与内涵道之比LEAP-1C 约 11:1"),
("风扇","风扇,fan","concept","涡扇发动机前部大直径旋转叶片LEAP-1C 有 18 片碳纤维叶片"),
("压气机","压气机,compressor","concept","压缩进入燃烧室前空气的旋转部件分低压和高压"),
("燃烧室","燃烧室,combustor","concept","燃料与高压空气混合燃烧的部件LEAP 采用 TAPS 低排放"),
("涡轮","涡轮,turbine","concept","利用高温燃气膨胀做功驱动压气机和风扇的旋转部件"),
("尾喷管","尾喷管,exhaust nozzle","concept","加速燃气排出产生推力的喷管"),
("推力","推力,thrust","concept","发动机产生的推进力LEAP-1C28 最大起飞推力 129.98 kN"),
("反推","反推,thrust reverser","concept","着陆时改变排气方向产生反向推力减速的装置"),
("短舱","短舱,nacelle","concept","包裹发动机的流线型外壳LEAP-1C 采用 Nexcelle 整体式短舱"),
])
gt("terms-engine-compressor-20260728-candidate.yaml","c919-graph-eng-cmp-v1","C919 压气机术语","按压气机结构拆分的术语","engcmp_",[
("压气机","压气机,compressor","concept","压缩进入空气的旋转部件提高空气压力和温度"),
("低压压气机","低压压气机,LPC","concept","由低压涡轮驱动的压气机前段对内涵气流初级压缩"),
("高压压气机","高压压气机,HPC","concept","由高压涡轮驱动的高转速压气机将空气压缩至高压"),
("压比","压比,pressure ratio","concept","压气机出口总压与进口总压之比LEAP-1C 总压比约 40:1"),
("级","级,stage","concept","压气机中一级转子加一级静子的组合单元"),
("叶片","叶片,blade","concept","压气机转子和静子上的翼型件改变气流方向和压力"),
("静子","静子,stator","concept","压气机中固定的导向叶片整流转子气流"),
("转子","转子,rotor","concept","压气机中旋转的叶片排对气流做功增加压力"),
("叶尖","叶尖,blade tip","concept","转子叶片顶端与机匣内壁之间的间隙影响效率"),
("喘振","喘振,surge","concept","压气机流量瞬间倒流引起剧烈振动的失稳现象"),
("失速","失速,stall","concept","压气机叶片上气流分离导致级性能下降"),
("防喘","防喘,surge protection","concept","通过可变静子放气活门和燃油调节防止喘振"),
])
gt("terms-engine-combustion-20260728-candidate.yaml","c919-graph-eng-cmb-v1","C919 燃烧室术语","按燃烧原理拆分的术语","engcmb_",[
("燃烧室","燃烧室,combustor","concept","燃料与高压空气混合燃烧的部件将化学能转化为热能"),
("TAPS","TAPS,twin annular premixing swirler","concept","LEAP 发动机双环预混旋流燃烧室技术大幅降低 NOx"),
("富油","富油,fuel rich","concept","燃烧混合气中燃油比例高于化学恰当比的状态"),
("贫油","贫油,fuel lean","concept","燃烧混合气中燃油比例低于化学恰当比的状态"),
("预混","预混,premixing","concept","燃油与空气在进入火焰区前预先混合降低 NOx"),
("旋流","旋流,swirl","concept","通过旋流器使空气旋转产生回流区稳定火焰"),
("火焰筒","火焰筒,flame tube,liner","concept","燃烧室内部容纳火焰的筒形结构壁面有冷却气膜"),
("燃油喷嘴","燃油喷嘴,fuel nozzle","concept","将燃油雾化喷入燃烧室的喷嘴LEAP 采用双环预混喷嘴"),
("点火","点火,ignition","concept","燃烧室中初始点燃混合气的电火花点火过程"),
("熄火","熄火,flameout","concept","燃烧室火焰因扰动或燃油中断而熄灭需重新点火"),
("NOx","NOx,氮氧化物","concept","高温燃烧产生的氮氧化物排放环保适航重点限制指标"),
("冒烟","冒烟,smoke","concept","不完全燃烧产生的碳烟颗粒排放影响环境"),
])
gt("terms-engine-turbine-20260728-candidate.yaml","c919-graph-eng-tbn-v1","C919 涡轮术语","按涡轮结构拆分的术语","engtbn_",[
("涡轮","涡轮,turbine","concept","利用高温燃气膨胀做功驱动压气机和风扇的旋转部件"),
("高压涡轮","高压涡轮,HPT","concept","驱动高压压气机的高转速涡轮工作温度最高"),
("低压涡轮","低压涡轮,LPT","concept","驱动风扇和低压压气机的涡轮级数较多转速较低"),
("导向器","导向器,NGV,nozzle guide vane","concept","涡轮进口固定导向叶片将燃气加速引导至转子叶片"),
("转子叶片","转子叶片,rotor blade,涡轮叶片","concept","涡轮中旋转做功的翼型件承受高温和高离心应力"),
("静子叶片","静子叶片,stator vane","concept","涡轮级间固定导向叶片整流气流为下级预旋"),
("叶尖间隙","叶尖间隙,tip clearance","concept","涡轮转子叶尖与机匣间隙越小效率越高"),
("冷却","冷却,cooling","concept","通过内部气膜和冲压空气降低涡轮叶片温度的技术"),
("气膜冷却","气膜冷却,film cooling","concept","在叶片表面形成冷却气膜隔热燃气保护叶片"),
("热应力","热应力,thermal stress","concept","温度梯度导致材料内部产生的不均匀热膨胀应力"),
("蠕变","蠕变,creep","concept","高温下材料在持续应力下缓慢永久变形是叶片寿命限制"),
("疲劳","疲劳,fatigue,热疲劳","concept","交变温度和机械载荷下涡轮叶片产生裂纹的疲劳现象"),
])
gt("terms-engine-fadec-20260728-candidate.yaml","c919-graph-eng-fadec-v1","C919 FADEC 术语","按发动机控制拆分的术语","engfd_",[
("FADEC","FADEC,全权限数字式发动机控制","concept","发动机全权限数字式电子控制系统C919 LEAP-1C 由其管理"),
("EEC","EEC,electronic engine control","concept","FADEC 核心计算机实时处理传感器数据控制燃油流量"),
("ECU","ECU,engine control unit","concept","发动机控制单元管理发动机运行参数"),
("燃油控制","燃油控制,fuel control","concept","FADEC 根据推力指令和工况精确计量燃油流量"),
("推力管理","推力管理,thrust management","concept","FADEC 根据 PLA 指令和环境条件计算输出目标推力"),
("自动推力","自动推力,autothrottle,A/T","concept","飞控与 FADEC 协同自动调节推力保持速度或推力模式"),
("反推控制","反推控制,reverser control","concept","FADEC 管理反推装置打开和关闭时序的功能"),
("启动控制","启动控制,start control","concept","FADEC 控制发动机启动过程中点火和燃油供入时序"),
("监控","监控,monitoring","concept","FADEC 实时监测发动机参数并在超限时告警"),
("余度","余度,redundancy","concept","FADEC 采用双通道余度设计一个失效仍可安全工作"),
("BITE","BITE,built-in test equipment","concept","FADEC 内置自检测功能自动诊断故障并记录维护信息"),
("软件","软件,software","concept","FADEC 运行的控制算法程序按 DO-178C 标准开发验证"),
])
gt("terms-materials-aluminum-20260728-candidate.yaml","c919-graph-mat-al-v1","C919 铝合金术语","按铝合金类型拆分的术语","matal_",[
("铝合金","铝合金,aluminum alloy","concept","以铝为基添加铜锌锂等元素的轻质结构合金"),
("铝锂合金","铝锂合金,Al-Li alloy","concept","添加锂元素降低密度提高模量的先进铝合金C919 占比 8.8%"),
("2024","2024,2024 铝合金","concept","铝铜系高韧性合金传统飞机蒙皮和下翼面常用材料"),
("7075","7075,7075 铝合金","concept","铝锌镁铜系高强度合金用于机翼上蒙皮和高应力结构"),
("硬度","硬度,hardness","concept","材料抵抗局部压入变形的能力铝合金通过热处理提高"),
("强度","强度,strength","concept","材料抵抗变形和断裂的能力分屈服强度和极限强度"),
("韧性","韧性,toughness","concept","材料抵抗裂纹扩展的能力飞机结构要求高断裂韧性"),
("疲劳","疲劳,fatigue","concept","交变载荷下铝合金产生裂纹的疲劳性能是机身耐久性关键"),
("腐蚀","腐蚀,corrosion","concept","铝合金与环境发生电化学反应导致材料劣化"),
("阳极氧化","阳极氧化,anodizing","concept","电化学方法在铝合金表面形成氧化膜提高耐腐蚀性"),
("热处理","热处理,heat treatment","concept","通过控制加热冷却改变铝合金内部组织和性能的工艺"),
("时效","时效,aging","concept","铝合金在特定温度保持使溶质原子析出强化相提高强度"),
])
gt("terms-materials-composite-20260728-candidate.yaml","c919-graph-mat-cmp-v1","C919 复合材料术语","按复合材料类型拆分的术语","matcmp_",[
("复合材料","复合材料,composite material","concept","由两种或多种材料组合形成优于各组分性能的材料C919 占比 12%"),
("碳纤维","碳纤维,carbon fiber,CF","concept","高强高模量纤维C919 垂尾和方向舵采用碳纤维复合材料"),
("玻璃纤维","玻璃纤维,glass fiber,GF","concept","成本低韧性好的纤维用于次结构和内饰复合材料"),
("环氧树脂","环氧树脂,epoxy resin","concept","复合材料中最常用的热固性基体树脂与碳纤维形成 CFRP"),
("预浸料","预浸料,prepreg","concept","纤维预先浸渍树脂并冷藏保存的中间材料使用时铺贴固化"),
("铺层","铺层,layup,ply","concept","将预浸料按设计方向和顺序逐层铺设的工艺"),
("固化","固化,cure","concept","通过加热加压使树脂交联硬化的工艺通常在热压罐进行"),
("RTM","RTM,resin transfer molding","concept","将干纤维放入模具后注入树脂固化的成型工艺"),
("蜂窝","蜂窝,honeycomb","concept","六边形蜂窝结构的轻质芯材与面板组成夹层结构"),
("夹层","夹层,sandwich structure","concept","两面薄面板中间夹蜂窝或泡沫芯的轻质高刚度结构"),
("各向异性","各向异性,anisotropy","concept","材料性能随方向不同的特性复合材料沿纤维方向强度高"),
("层间剪切","层间剪切,interlaminar shear","concept","复合材料层间界面的剪切强度是铺层设计的薄弱环节"),
])
gt("terms-materials-titanium-20260728-candidate.yaml","c919-graph-mat-ti-v1","C919 钛合金术语","按钛合金类型拆分的术语","matti_",[
("钛合金","钛合金,titanium alloy","concept","以钛为基的高强耐腐蚀高温合金C919 在吊架和高温区使用"),
("Ti-6Al-4V","Ti-6Al-4V,TC4","concept","应用最广泛的 αβ 型钛合金兼顾强度韧性和可加工性"),
("密度","密度,density","concept","钛合金密度约 4.5 g/cm³介于铝合金和钢之间比强度高"),
("强度","强度,strength","concept","钛合金抗拉强度可达 1000 MPa 以上高温强度保持性好"),
("耐腐蚀","耐腐蚀,corrosion resistance","concept","钛合金表面致密氧化膜使其在海洋和高温环境耐腐蚀优异"),
("高温","高温,high temperature","concept","钛合金可在 400-600°C 长期工作用于发动机热端和防火区"),
("相变","相变,phase transformation","concept","钛合金在 882°C 发生 α 到 β 相的同素异构转变"),
("α合金","α合金,alpha alloy","concept","密排六方 α 相钛合金可焊性好但强度中等用于高温耐蚀"),
("β合金","β合金,beta alloy","concept","体心立方 β 相钛合金强度高可时效强化高温稳定性较差"),
("αβ合金","αβ合金,alpha-beta alloy","concept","含 α 和 β 两相的钛合金综合性能最佳Ti-6Al-4V 属此类"),
("热处理","热处理,heat treatment","concept","通过固溶和时效调节钛合金两相比例和性能的工艺"),
("焊接","焊接,welding","concept","钛合金可采用 TIG 电子束和扩散焊需严格防氧化"),
])
gt("terms-materials-manufacturing-20260728-candidate.yaml","c919-graph-mat-mfg-v1","C919 材料制造术语","按制造工艺拆分的术语","matmfg_",[
("锻造","锻造,forging","concept","通过冲击或压力使金属塑性变形成形的工艺C919 起落架采用"),
("铸造","铸造,casting","concept","将熔融金属浇入模具凝固成形的工艺适合复杂形状"),
("机加","机加,machining,CNC 加工","concept","通过切削去除多余材料的精密加工方法C919 采用五轴数控"),
("钣金","钣金,sheet metal forming","concept","通过弯曲拉伸和冲压成形薄金属板的工艺机身蒙皮采用"),
("挤压","挤压,extrusion","concept","将加热金属通过模具挤出特定截面长条的工艺桁条采用"),
("轧制","轧制,rolling","concept","金属通过旋转轧辊间减薄成板的工艺蒙皮板材由轧制生产"),
("热处理","热处理,heat treatment","concept","通过控制加热冷却改善材料性能的工艺"),
("表面处理","表面处理,surface treatment","concept","在零件表面施加防护层提高耐腐蚀和耐磨性的工艺"),
("无损检测","无损检测,NDT","concept","不损坏零件前提下检测内部缺陷的方法航空件 100% 检测"),
("超声","超声,ultrasonic testing,UT","concept","利用超声波在材料中反射检测内部缺陷的无损检测方法"),
("渗透","渗透,penetrant testing,PT","concept","利用荧光渗透液显示表面开口裂纹的无损检测方法"),
("射线","射线,radiographic testing,RT","concept","利用 X 射线穿透材料检测内部缺陷的无损检测方法"),
])
gt("terms-materials-fastener-20260728-candidate.yaml","c919-graph-mat-fst-v1","C919 紧固件术语","按紧固件类型拆分的术语","matfst_",[
("铆钉","铆钉,rivet","concept","永久性不可拆卸的金属销钉C919 机身蒙皮与桁条大量铆接"),
("螺栓","螺栓,bolt","concept","可拆卸的螺纹紧固件C919 关键结构连接采用航空高强度螺栓"),
("螺母","螺母,nut","concept","与螺栓配合使用的螺纹紧固件航空螺母通常带自锁功能"),
("垫圈","垫圈,washer","concept","分散螺栓预紧力并保护被连接件表面的环形薄片"),
("销","销,pin,销轴","concept","用于铰接或定位的无螺纹圆柱紧固件C919 操纵接头采用"),
("卡箍","卡箍,clamp","concept","固定管路和线缆的环抱式紧固件"),
("高锁螺栓","高锁螺栓,hi-lock bolt,Hi-Lok","concept","带断颈槽控制的单面安装高强度螺栓C919 机翼机身大量使用"),
("盲铆","盲铆,blind rivet","concept","仅从一侧即可安装的铆钉用于封闭结构内部无法触及的连接"),
("拉伸","拉伸,tension","concept","紧固件沿轴线受拉的载荷类型螺栓须满足拉伸强度要求"),
("剪切","剪切,shear","concept","紧固件受横向力剪切的载荷类型铆钉螺栓大多按剪切设计"),
("预紧力","预紧力,preload","concept","安装时施加使紧固件预先受拉的力防止松动并提高疲劳寿命"),
("防松","防松,locking","concept","防止螺母使用中松脱的措施包括自锁螺母保险丝和开口销"),
])
# === END TERMS DATA ===
# === ENTITIES DATA ===
ge("entities-aircraft-c919-variants-20260728-candidate.yaml","c919-graph-ent-ac-variants-v1","C919 变体机型实体","按 C919 改型拆分的实体","acvar_",[
("acvar_c919_100std","aircraft","C919-100STD","C919-100STD,C919 标准型","C919 系列基本标准型 2022-09-29 取得型号合格证",[("wingspan_m",35.8),("length_m",38.9),("mtow_kg",77300),("range_km",4075),("seats","158-168"),("cruise_mach",0.785),("engines","2× LEAP-1C28")]),
("acvar_c919_100er","aircraft","C919-100ER","C919-100ER,C919 延程型","C919 系列延程型增加燃油容量提升 MTOW 实现更远航程",[("wingspan_m",35.8),("length_m",38.9),("mtow_kg",78900),("range_km",5555),("seats","158-168"),("cruise_mach",0.785),("engines","2× LEAP-1C30")]),
("acvar_c919_600","aircraft","C919-600","C919-600,C919 缩短型","C919 系列缩短型面向中短程高密度市场",[("wingspan_m",35.8),("length_m",35.5),("mtow_kg",75000),("range_km",4100),("seats","140-150"),("cruise_mach",0.785),("engines","2× LEAP-1C")]),
("acvar_c919_800","aircraft","C919-800","C919-800,C919 加长型","C919 系列加长型机身加长约 4 米面向大客流市场",[("wingspan_m",35.8),("length_m",42.8),("mtow_kg",80000),("range_km",3900),("seats","180-192"),("cruise_mach",0.785),("engines","2× LEAP-1C")]),
("acvar_c919_100f","aircraft","C919-100F","C919-100F,C919 货机,C919F","C919 系列货机改型拆除客舱内饰安装货舱滚装系统",[("mtow_kg",78000),("payload_kg",25000),("range_km",3500),("engines","2× LEAP-1C")]),
("acvar_c919_100bj","aircraft","C919-100BJ","C919-100BJ,C919 公务机","C919 系列公务机改型客舱改为 VIP 布局增设辅助油箱",[("mtow_kg",78900),("range_km",6500),("passengers","26-50"),("engines","2× LEAP-1C")]),
("acvar_c919_100lr","aircraft","C919-100LR","C919-100LR,C919 远程型","C919 系列远程型增加燃油容量和 MTOW 实现更长航程",[("mtow_kg",80000),("range_km",6500),("engines","2× LEAP-1C")]),
("acvar_c919_100x","aircraft","C919-100X","C919-100X,C919 加长研究型","C919 系列加长研究型概念方案机身加长至 200 座以上",[("mtow_kg",82000),("seats","200-210"),("engines","2× LEAP-1C")]),
])
ge("entities-aircraft-competitors-20260728-candidate.yaml","c919-graph-ent-ac-comp-v1","C919 竞争机型实体","按对标机型拆分的实体","accomp_",[
("accomp_a320","aircraft","空客 A320","A320,A320ceo,Airbus A320","空客 A320 CEO 窄体客机 C919 直接对标机型",[("wingspan_m",35.8),("length_m",37.57),("mtow_kg",78000),("range_km",6100),("seats","150-180"),("cruise_mach",0.78),("engines","2× CFM56-5B 或 V2500")]),
("accomp_a319","aircraft","空客 A319","A319,A319ceo","空客 A319 缩短型窄体客机 C919-600 潜在竞争机型",[("wingspan_m",35.8),("length_m",33.84),("mtow_kg",75000),("range_km",6700),("seats","124-156"),("cruise_mach",0.78),("engines","2× CFM56-5B")]),
("accomp_a321","aircraft","空客 A321","A321,A321ceo","空客 A321 加长型窄体客机 C919-800 潜在竞争机型",[("wingspan_m",35.8),("length_m",44.51),("mtow_kg",89000),("range_km",5950),("seats","170-220"),("cruise_mach",0.78),("engines","2× CFM56-5B")]),
("accomp_a320neo","aircraft","空客 A320neo","A320neo,A320 NEO","空客 A320 NEO 换发型燃油效率提升约 15%",[("wingspan_m",35.8),("length_m",37.57),("mtow_kg",79000),("range_km",6500),("seats","150-194"),("cruise_mach",0.78),("engines","2× LEAP-1A 或 PW1100G")]),
("accomp_a321neo","aircraft","空客 A321neo","A321neo,A321 NEO","空客 A321 NEO 换发型加长型 C919-800 主要竞争机型",[("wingspan_m",35.8),("length_m",44.51),("mtow_kg",89000),("range_km",7400),("seats","180-220"),("cruise_mach",0.78),("engines","2× LEAP-1A 或 PW1100G")]),
("accomp_b737_800","aircraft","波音 737-800","B737-800,737-800,Boeing 737-800","波音 737NG 主力窄体客机 C919 直接竞争机型",[("wingspan_m",35.79),("length_m",39.5),("mtow_kg",79010),("range_km",5765),("seats","162-189"),("cruise_mach",0.785),("engines","2× CFM56-7B")]),
("accomp_b737max8","aircraft","波音 737 MAX 8","B737MAX8,737 MAX 8,Boeing 737 MAX 8","波音 737 MAX 换发型主力机型",[("wingspan_m",35.92),("length_m",39.52),("mtow_kg",82200),("range_km",6570),("seats","162-210"),("cruise_mach",0.79),("engines","2× CFM LEAP-1B")]),
("accomp_b737max9","aircraft","波音 737 MAX 9","B737MAX9,737 MAX 9","波音 737 MAX 加长型 C919-800 竞争机型",[("wingspan_m",35.92),("length_m",42.16),("mtow_kg",88300),("range_km",6550),("seats","178-220"),("cruise_mach",0.79),("engines","2× CFM LEAP-1B")]),
("accomp_b737_700","aircraft","波音 737-700","B737-700,737-700","波音 737NG 缩短型 C919-600 竞争机型",[("wingspan_m",35.79),("length_m",33.63),("mtow_kg",70100),("range_km",6230),("seats","126-149"),("cruise_mach",0.785),("engines","2× CFM56-7B")]),
("accomp_e190","aircraft","巴航工业 E190","E190,Embraer E190","巴航工业 100 座级支线客机 C919 间接竞争机型",[("wingspan_m",28.72),("length_m",36.24),("mtow_kg",51800),("range_km",4537),("seats","96-114"),("cruise_mach",0.78),("engines","2× GE CF34-10E")]),
])
ge("entities-aircraft-chinese-20260728-candidate.yaml","c919-graph-ent-ac-cn-v1","中国机型实体","按中国民机拆分的实体","accn_",[
("accn_c919","aircraft","C919","C919,国产大飞机","中国商飞 158-192 座级窄体干线客机 2022-09-29 取得 TC",[("wingspan_m",35.8),("length_m",38.9),("height_m",11.95),("mtow_kg",77300),("range_km",4075),("seats","158-168"),("cruise_mach",0.785),("engines","2× LEAP-1C28")]),
("accn_arj21","aircraft","ARJ21-700","ARJ21,ARJ21-700,翔凤","中国商飞 78-90 座级支线喷气客机 C919 前期技术积累",[("wingspan_m",27.29),("length_m",33.46),("mtow_kg",43000),("range_km",3700),("seats","78-90"),("cruise_mach",0.78),("engines","2× GE CF34-10A")]),
("accn_c909","aircraft","中国商飞 C909","C909,ARJ21 改名","ARJ21-700 更名后的中国商飞 C909 系列支线客机",[("wingspan_m",27.29),("length_m",33.46),("mtow_kg",43000),("range_km",3700),("seats","78-90"),("cruise_mach",0.78),("engines","2× GE CF34-10A")]),
("accn_cr929","aircraft","CR929","CR929,中俄远程宽体客机","中俄合作研制的 280-320 座级远程宽体客机项目",[("wingspan_m",62.0),("length_m",63.3),("seats","280-320"),("cruise_mach",0.85),("engines","TBD")]),
("accn_ma60","aircraft","新舟 60","MA60,新舟60,Modern Ark 60","中国西飞 50-60 座级双涡桨支线客机",[("wingspan_m",29.2),("length_m",24.71),("mtow_kg",21800),("range_km",1600),("seats","50-60"),("cruise_mach",0.50),("engines","2× PW127J")]),
("accn_ma700","aircraft","新舟 700","MA700,新舟700","中国西飞新一代 70-80 座级双涡桨支线客机",[("wingspan_m",30.9),("length_m",28.05),("seats","70-78"),("engines","2× PW150C")]),
("accn_y12","aircraft","运-12","运-12,Y-12,Harbin Y-12","中国哈飞 17-19 座级双涡桨通用飞机",[("wingspan_m",17.24),("length_m",14.86),("mtow_kg",5300),("seats","17-19"),("engines","2× PT6A-27")]),
("accn_ag600","aircraft","AG600","AG600,鲲龙,大型水陆两栖飞机","中国通飞大型水陆两栖救援飞机世界最大在研水陆两栖机",[("wingspan_m",38.8),("length_m",37.0),("mtow_kg",53000),("range_km",4500),("engines","4× WJ-6")]),
])
ge("entities-components-wing-20260728-candidate.yaml","c919-graph-ent-comp-wing-v1","C919 机翼部件实体","按机翼部件拆分的实体","ecwg_",[
("ecwg_wing","component","机翼","wing,主翼,C919 机翼","C919 产生升力的主要气动部件翼展 33.6m 含小翼 35.8m 超临界翼型",[("wingspan_m",35.8),("sweep_deg",25),("aspect_ratio",9.5)]),
("ecwg_center_wingbox","component","中央翼盒","center wing box,中央翼,中翼盒","机身中部贯穿的机翼承力盒段连接左右机翼并作为中央油箱",[]),
("ecwg_outer_wing","component","外翼","outer wing,外翼段","中央翼盒以外至翼尖的机翼段承受飞行气动载荷",[]),
("ecwg_flap","component","襟翼","flap,后缘襟翼,富勒襟翼","机翼后缘内侧可偏转增升装置采用富勒式设计",[]),
("ecwg_slat","component","缝翼","slat,前缘缝翼","机翼前缘可伸出增升装置延缓大迎角失速",[]),
("ecwg_aileron","component","副翼","aileron,副翼操纵面","机翼后缘外侧可动翼面差动偏转实现滚转操纵",[]),
("ecwg_spoiler","component","扰流板","spoiler,减速板,地面扰流板","机翼上表面可向上偏转的板面空中减速辅助滚转",[]),
("ecwg_winglet","component","翼尖小翼","winglet,翼梢小翼","安装在翼尖的倾斜翼面减弱翼尖涡流降低诱导阻力",[]),
("ecwg_front_spar","component","前梁","front spar,前缘梁","翼盒前部展向主梁承受主要剪力",[]),
("ecwg_rear_spar","component","后梁","rear spar,后缘梁","翼盒后部展向主梁为襟翼副翼提供安装接口",[]),
("ecwg_rib","component","翼肋","rib","机翼弦向构件维持翼型形状并传递载荷给翼梁",[]),
("ecwg_stringer","component","桁条","stringer,长桁","机翼展向纵向构件支持蒙皮承受压缩载荷",[]),
("ecwg_skin","component","蒙皮","skin,机翼蒙皮","机翼上下表面薄壁结构承受扭转和部分弯曲载荷",[("material","铝合金")]),
("ecwg_wing_root","component","翼根","wing root,翼根接头","机翼与中央翼盒连接区域承受最大弯矩",[]),
("ecwg_wingtip","component","翼尖","wing tip,翼梢","机翼最外侧端部安装翼尖小翼",[]),
])
ge("entities-components-fuselage-20260728-candidate.yaml","c919-graph-ent-comp-fus-v1","C919 机身部件实体","按机身部件拆分的实体","ecfus_",[
("ecfus_fwd_fuselage","component","前机身","forward fuselage,机头段","机身前段结构含驾驶舱雷达罩和前起落架舱",[]),
("ecfus_mid_fuselage","component","中机身","mid fuselage,center fuselage","机身中段结构连接中央翼盒承载主客舱和主起落架舱",[]),
("ecfus_aft_fuselage","component","后机身","aft fuselage,机身后段","机身后段结构含 APU 舱和尾椎",[]),
("ecfus_pressure_bulkhead","component","气密框","pressure bulkhead,后气密框","机身增压区后端的球形承力隔框分隔增压舱与尾椎",[]),
("ecfus_stringer","component","桁条","stringer,机身长桁","机身纵向骨架构件传递轴向载荷",[]),
("ecfus_skin","component","蒙皮","skin,机身蒙皮","机身外表面薄壁结构机身宽度 3.96m 采用铝锂合金",[("fuselage_width_m",3.96),("material","铝锂合金")]),
("ecfus_floor_beam","component","地板梁","floor beam,地板横梁","支撑客舱地板的横向梁结构",[]),
("ecfus_passenger_door","component","客舱门","passenger door,登机门","机身左侧前部和中部主登机门",[]),
("ecfus_cargo_door","component","货舱门","cargo door","机身右侧前腹货舱大型外开舱门",[]),
("ecfus_emergency_exit","component","紧急出口","emergency exit,应急出口","机身两侧翼上和翼后紧急撤离出口",[]),
("ecfus_windshield","component","风挡","windshield,驾驶舱风挡","驾驶舱正前方多层电加热透明风挡玻璃",[]),
("ecfus_cabin","component","客舱","cabin,passenger cabin","机身内旅客乘坐的增压舱段 158-192 座",[("seats","158-192"),("layout","3-3")]),
("ecfus_cargo_hold","component","货舱","cargo hold","机身下部行李货物运输舱段",[]),
("ecfus_cockpit","component","驾驶舱","cockpit,flight deck","机身前部飞行机组操作舱配备侧杆和电子显示器",[]),
("ecfus_radome","component","雷达罩","radome,机头雷达罩","机身最前端容纳气象雷达天线的透波整流罩",[]),
])
ge("entities-components-empennage-20260728-candidate.yaml","c919-graph-ent-comp-emp-v1","C919 尾翼部件实体","按尾翼部件拆分的实体","ecemp_",[
("ecemp_vtail","component","垂直尾翼","vertical tail,垂尾,fin","尾翼垂直翼面提供航向稳定性后缘安装方向舵",[("sweep_deg",35)]),
("ecemp_htail","component","水平尾翼","horizontal tail,平尾","尾翼水平翼面提供纵向稳定性C919 采用低平尾布局",[]),
("ecemp_rudder","component","方向舵","rudder","垂直尾翼后缘可动翼面控制偏航运动",[]),
("ecemp_elevator","component","升降舵","elevator","水平尾翼后缘可动翼面控制俯仰运动",[]),
("ecemp_stabilizer","component","安定面","stabilizer","尾翼中固定翼面部分提供稳定性基线",[]),
("ecemp_trim_tab","component","配平片","trim tab","舵面后缘可调小翼面减小或消除操纵杆力",[]),
("ecemp_ventral_fin","component","腹鳍","ventral fin","机身尾部下方垂直翼面增强航向稳定性",[]),
("ecemp_dorsal_fin","component","背鳍","dorsal fin","机身尾部至垂尾根部整流翼面",[]),
("ecemp_tail_root","component","尾翼翼根","tail root","尾翼与机身连接区域承受尾翼弯矩和剪力",[]),
("ecemp_tail_tip","component","尾翼翼尖","tail tip","尾翼最外侧端部",[]),
("ecemp_swept_tail","component","后掠尾翼","swept tail","具有后掠角的尾翼构型延缓压缩性效应",[]),
("ecemp_adjustable_stab","component","可调安定面","adjustable stabilizer","安装角可调的水平安定面用于飞行中纵向配平",[]),
])
ge("entities-components-landing-gear-20260728-candidate.yaml","c919-graph-ent-comp-lg-v1","C919 起落架部件实体","按起落架部件拆分的实体","eclg_",[
("eclg_nose_gear","component","前起落架","nose landing gear,NLG,前起","前机身下方可收放起落架双轮式提供地面转向操纵",[("wheels",2)]),
("eclg_main_gear","component","主起落架","main landing gear,MLG,主起","机身中部下方可收放起落架左右各一套四轮式",[("wheels_per_side",4)]),
("eclg_wheel","component","机轮","wheel","起落架接地滚动部件",[]),
("eclg_brake","component","刹车","brake,碳刹车","机轮内多盘式碳-钢刹车组件",[("type","carbon")]),
("eclg_tire","component","轮胎","tire","机轮外圈充气橡胶轮胎",[]),
("eclg_shock_strut","component","减震支柱","shock strut,oleo strut","起落架主缓冲结构通过油气压缩吸收着陆冲击",[]),
("eclg_retraction","component","收放机构","retraction mechanism","起落架液压驱动的收放装置",[]),
("eclg_steering","component","转弯机构","steering mechanism","前起落架液压转弯系统",[]),
("eclg_gear_door","component","舱门","gear door","覆盖起落架舱开口的结构门",[]),
("eclg_strut","component","支柱","strut","起落架主要承力柱状结构",[]),
("eclg_rocker_arm","component","摇臂","rocker arm","连接起落架内外筒的连杆",[]),
("eclg_torque_link","component","扭力臂","torque link","起落架缓冲支柱上下段连杆组件",[]),
])
ge("entities-components-engine-20260728-candidate.yaml","c919-graph-ent-comp-eng-v1","C919 发动机部件实体","按发动机部件拆分的实体","eceng_",[
("eceng_fan","component","风扇","fan,发动机风扇","涡扇发动机前部大直径旋转叶片 LEAP-1C 有 18 片碳纤维叶片",[("blades",18),("material","碳纤维复合材料")]),
("eceng_lpc","component","低压压气机","LPC,low pressure compressor","由低压涡轮驱动的压气机前段对内涵气流初级压缩",[]),
("eceng_hpc","component","高压压气机","HPC,high pressure compressor","由高压涡轮驱动的高转速压气机将空气压缩至高压",[("pressure_ratio","40:1 (total)")]),
("eceng_combustor","component","燃烧室","combustor,TAPS 燃烧室","燃料与高压空气混合燃烧的部件 LEAP 采用 TAPS 低排放技术",[("type","TAPS")]),
("eceng_hpt","component","高压涡轮","HPT,high pressure turbine","驱动高压压气机的高转速涡轮工作温度最高",[]),
("eceng_lpt","component","低压涡轮","LPT,low pressure turbine","驱动风扇和低压压气机的涡轮",[]),
("eceng_nozzle","component","尾喷管","nozzle,exhaust nozzle","加速燃气排出产生推力的喷管",[]),
("eceng_thrust_reverser","component","反推装置","thrust reverser,反推","着陆时改变排气方向产生反向推力的装置",[]),
("eceng_nacelle","component","短舱","nacelle,PANACHE 短舱","包裹发动机的流线型外壳采用 Nexcelle 整体式短舱",[("supplier","Nexcelle")]),
("eceng_inlet","component","进气道","inlet","发动机前部将空气整流加速进入风扇的通道",[]),
("eceng_fan_blade","component","风扇叶片","fan blade,碳纤维风扇叶片","LEAP-1C 风扇的 18 片碳纤维复合材料叶片",[("count",18),("material","碳纤维复合材料")]),
("eceng_ngv","component","导向器","NGV,nozzle guide vane","涡轮进口固定导向叶片将燃气加速引导至转子叶片",[]),
("eceng_rotor","component","转子","rotor,涡轮转子","涡轮中旋转做功的部件",[]),
("eceng_stator","component","静子","stator","压气机或涡轮中固定的导向叶片",[]),
("eceng_bearing","component","轴承","bearing","支撑发动机转子的滚动轴承",[]),
])
ge("entities-components-cabin-20260728-candidate.yaml","c919-graph-ent-comp-cabin-v1","C919 客舱部件实体","按客舱部件拆分的实体","eccab_",[
("eccab_seat","component","座椅","seat,旅客座椅","客舱旅客座椅 C919 典型 3-3 经济舱布局 158-192 座",[("layout","3-3"),("seats","158-192")]),
("eccab_overhead_bin","component","行李架","overhead bin,行李箱","客舱顶部存放旅客手提行李的封闭式储物架",[]),
("eccab_ceiling_light","component","顶灯","ceiling light,客舱顶灯","客舱天花板 LED 照明灯可调光色温",[("type","LED")]),
("eccab_vent","component","通风口","vent,空气出口","旅客头顶上方的个人空气出口",[]),
("eccab_oxygen_mask","component","氧气面罩","oxygen mask","客舱旅客供氧面罩座舱高度超 14000ft 时自动落下",[]),
("eccab_ife","component","机上娱乐","IFE,in-flight entertainment","客舱座椅背板上方的娱乐显示屏和音频系统",[]),
("eccab_galley","component","厨房","galley,机舱厨房","客舱前部和中部供餐准备区",[]),
("eccab_lavatory","component","卫生间","lavatory,盥洗室","客舱旅客卫生间配备真空马桶和洗手池",[]),
("eccab_evac_slide","component","应急滑梯","evacuation slide","舱门处充气式应急撤离滑梯",[]),
("eccab_life_vest","component","救生衣","life vest","每名旅客座椅下配备的充气式救生衣",[]),
("eccab_door","component","舱门","cabin door,客舱门","客舱主登机门和应急出口门",[]),
("eccab_window","component","窗户","window,客舱舷窗","客舱侧壁旅客观景窗户多层有机玻璃",[]),
])
ge("entities-systems-propulsion-20260728-candidate.yaml","c919-graph-ent-sys-prop-v1","C919 推进系统实体","按推进系统拆分的实体","esprop_",[
("esprop_leap1c28","system","LEAP-1C28","LEAP-1C28,CFM LEAP-1C28","CFM 国际为 C919 标准型提供的涡扇发动机最大起飞推力 129.98 kN",[("bypass_ratio","11:1"),("mto_thrust_kn",129.98),("mct_thrust_kn",127.93),("fan_blades",18),("supplier","CFM International")]),
("esprop_leap1c30","system","LEAP-1C30","LEAP-1C30,CFM LEAP-1C30","CFM 国际为 C919 延程型提供的推力升级版最大起飞推力 137.14 kN",[("bypass_ratio","11:1"),("mto_thrust_kn",137.14),("mct_thrust_kn",133.22),("fan_blades",18),("supplier","CFM International")]),
("esprop_cj1000a","system","CJ-1000A","CJ-1000A,长江-1000A","中国航发研制的 C919 国产替代涡扇发动机",[("supplier","AECC")]),
("esprop_fuel_system","system","燃油系统","fuel system,燃油供给系统","C919 燃油储存与供给系统总容量约 19156 升",[("total_capacity_l",19156),("supplier","Parker Aerospace")]),
("esprop_nacelle","system","短舱系统","nacelle system,整体式短舱","包裹发动机的流线型外壳及其附件系统",[("supplier","Nexcelle")]),
("esprop_thrust_reverser","system","反推系统","thrust reverser","着陆时改变排气方向产生反向推力的装置",[]),
("esprop_pylon","system","发动机吊架","pylon,吊挂","连接发动机与机翼的结构承力件",[]),
("esprop_inlet","system","进气道系统","inlet","发动机前部整流进气通道",[]),
("esprop_exhaust","system","排气系统","exhaust","发动机燃气排出和降噪系统",[]),
("esprop_thrust_mgmt","system","推力管理","thrust management","FADEC 推力计算和输出管理功能",[]),
])
ge("entities-systems-flight-control-20260728-candidate.yaml","c919-graph-ent-sys-fc-v1","C919 飞控系统实体","按飞控元件拆分的实体","esfc_",[
("esfc_fcc","system","飞控计算机","FCC,flight control computer","C919 主飞控计算机执行控制律运算和余度管理",[("redundancy","三余度")]),
("esfc_actuator","system","作动器","actuator,液压作动器","飞控舵面液压作动器驱动副翼升降舵等",[]),
("esfc_servo","system","舵机","servo,伺服舵机","电液伺服舵机将电信号转换为液压输出",[]),
("esfc_sidestick","system","驾驶杆","sidestick,侧杆","驾驶舱侧置式电传操纵杆",[]),
("esfc_rudder_pedal","system","脚蹬","rudder pedal","驾驶舱脚蹬控制方向舵和前轮转弯",[]),
("esfc_spoiler_act","system","扰流板作动器","spoiler actuator","驱动扰流板偏转的液压作动器",[]),
("esfc_flap_act","system","襟翼作动器","flap actuator","驱动襟翼伸缩偏转的液压作动器",[]),
("esfc_slat_act","system","缝翼作动器","slat actuator","驱动缝翼伸出收回的液压作动器",[]),
("esfc_trim_motor","system","配平马达","trim motor","驱动水平安定面配平的电动或液压马达",[]),
("esfc_feel_computer","system","感觉计算机","feel computer","模拟操纵杆力的计算机提供人工感觉力反馈",[]),
("esfc_envelope_prot","system","包线保护","envelope protection","自动限制飞行参数不超出安全边界的功能模块",[]),
("esfc_redundancy_mgmt","system","余度管理","redundancy management","飞控多通道余度表决和故障切换管理模块",[]),
])
ge("entities-systems-hydraulic-20260728-candidate.yaml","c919-graph-ent-sys-hyd-v1","C919 液压系统实体","按液压元件拆分的实体","eshyd_",[
("eshyd_edp","system","EDP","EDP,engine driven pump","由发动机附件齿轮箱驱动的液压泵主供压源",[("pressure_psi",3000)]),
("eshyd_emp","system","EMP","EMP,electric motor pump","电动机驱动的液压泵提供备份和地面液压动力",[]),
("eshyd_accumulator","system","蓄压器","accumulator","储存液压油和气体的压力容器提供峰值流量补充",[]),
("eshyd_reservoir","system","油箱","hydraulic reservoir","储存液压油的容器",[]),
("eshyd_pressure_sensor","system","压力传感器","pressure sensor","监测液压系统压力的传感器",[]),
("eshyd_actuator","system","作动器","hydraulic actuator","将液压能转换为直线运动的执行元件",[]),
("eshyd_servo_valve","system","伺服阀","servo valve","将电信号转换为液压流量控制的精密阀门",[]),
("eshyd_directional_valve","system","换向阀","directional valve","控制液压油流向的开关阀",[]),
("eshyd_relief_valve","system","溢流阀","relief valve","液压系统过压时自动开启泄油的安全保护阀",[]),
("eshyd_fluid","system","液压油","hydraulic fluid,Skydrol","磷酸酯抗燃液压油 C919 采用 Skydrol LD-4",[("type","Skydrol LD-4")]),
("eshyd_filter","system","过滤器","filter","去除液压油中颗粒污染物的过滤元件",[]),
("eshyd_ground_coupling","system","地面接头","ground coupling","地面液压车连接的地面供压接口",[]),
])
ge("entities-systems-fuel-20260728-candidate.yaml","c919-graph-ent-sys-fuel-v1","C919 燃油系统实体","按燃油元件拆分的实体","esfuel_",[
("esfuel_center_tank","system","中央油箱","center tank","位于中央翼盒内的油箱容量约 7600 升",[("capacity_l",7600)]),
("esfuel_left_wing_tank","system","左机翼油箱","left wing tank,LWT","左机翼盒段内油箱容量约 5780 升",[("capacity_l",5780)]),
("esfuel_right_wing_tank","system","右机翼油箱","right wing tank,RWT","右机翼盒段内油箱容量约 5780 升",[("capacity_l",5780)]),
("esfuel_refuel_port","system","加油口","refuel port","压力加油接口位于机翼下表面",[]),
("esfuel_defuel_port","system","抽油口","defuel port","抽油操作接口",[]),
("esfuel_transfer_pump","system","输油泵","transfer pump","油箱之间转输燃油的泵",[]),
("esfuel_quantity_sensor","system","油量传感器","fuel quantity sensor","测量油箱内燃油体积的电容式传感器",[]),
("esfuel_vent_system","system","通气系统","vent system","维持油箱内压力平衡的通气系统",[]),
("esfuel_obiggs","system","惰性气体发生器","OBIGGS,inert gas generator","向油箱空间充入富氮气体防止可燃的系统",[]),
("esfuel_filter","system","燃油过滤器","fuel filter","去除燃油中污染物的过滤元件",[]),
("esfuel_bypass_valve","system","旁通阀","bypass valve","油滤堵塞时旁通燃油的备用通道阀门",[]),
("esfuel_crossfeed_valve","system","交输阀","crossfeed valve","允许左右油箱交叉供油的阀门",[]),
])
ge("entities-systems-electrical-20260728-candidate.yaml","c919-graph-ent-sys-elec-v1","C919 电气系统实体","按电气元件拆分的实体","eselec_",[
("eselec_idg","system","IDG","IDG,integrated drive generator","发动机驱动的恒速恒频发电机输出 115V AC 400Hz",[("output","115V AC 400Hz")]),
("eselec_tru","system","变压整流器","TRU,transformer rectifier unit","将 115V AC 转换为 28V DC 的电力变换设备",[("output","28V DC")]),
("eselec_battery","system","蓄电池","battery,电瓶","储存电能的化学电池组镍镉电池",[("type","Ni-Cd")]),
("eselec_rat","system","RAT","RAT,ram air turbine","应急时弹出的风力涡轮发电机",[]),
("eselec_epu","system","EPU","EPU,emergency power unit","紧急情况提供有限电力和液压的辅助装置",[]),
("eselec_main_bus","system","主汇流条","main bus","电气系统主配电母线节点",[]),
("eselec_emergency_bus","system","应急汇流条","emergency bus","应急供电母线由蓄电池和 RAT 供电",[]),
("eselec_ground_power","system","地面电源","ground power,GPU","地面外部供电接口",[]),
("eselec_inverter","system","逆变器","inverter","将直流电转换为交流电的变换设备",[]),
("eselec_breaker","system","断路器","circuit breaker,CB","过流或短路时自动断开电路的保护装置",[]),
("eselec_panel","system","配电盘","distribution panel","集中安装断路器和继电器的配电板",[]),
("eselec_grounding","system","接地系统","grounding system","飞机结构参考零电位连接系统",[]),
])
ge("entities-systems-ecs-20260728-candidate.yaml","c919-graph-ent-sys-ecs-v1","C919 环控系统实体","按环控元件拆分的实体","esecs_",[
("esecs_pneumatic","system","引气系统","pneumatic system,bleed air system","从发动机和 APU 提取压缩空气的系统",[]),
("esecs_pack","system","空调组件","air conditioning pack","对引气进行制冷和调温的成套设备",[("count",2)]),
("esecs_heat_exchanger","system","热交换器","heat exchanger","空调组件中冷热气流热交换的散热器",[]),
("esecs_acm","system","空气循环机","ACM,air cycle machine","利用涡轮膨胀降温的制冷核心部件",[]),
("esecs_water_separator","system","水分离器","water separator","从冷气流中分离冷凝水分的装置",[]),
("esecs_pressurization","system","座舱增压系统","pressurization system","维持座舱高于外部气压的系统",[("max_cabin_altitude_m",2400)]),
("esecs_pressure_regulator","system","压力调节阀","pressure regulator,outflow valve","调节排气阀开度控制座舱压力的阀门",[]),
("esecs_temp_control_valve","system","温度控制阀","temperature control valve","调节冷热空气混合比例控制送风温度的阀门",[]),
("esecs_ram_air","system","冲压空气系统","ram air system","利用飞行速度引入外界空气用于散热和应急通风",[]),
("esecs_oat_sensor","system","OAT 传感器","OAT sensor","测量飞机外部环境温度的传感器",[]),
("esecs_filter","system","过滤器","filter,HEPA filter","客舱送风 HEPA 高效过滤器",[("type","HEPA")]),
("esecs_humidity_control","system","湿度控制","humidity control","调节客舱湿度的系统",[]),
])
ge("entities-systems-avionics-20260728-candidate.yaml","c919-graph-ent-sys-avn-v1","C919 航电系统实体","按航电元件拆分的实体","esavn_",[
("esavn_ima_core","system","IMA 核心","IMA core,综合模块化航电核心","C919 航电计算共享平台核心处理模块",[("supplier","AVIAGE Systems")]),
("esavn_display","system","显示单元","display unit,DU","C919 驾驶舱 6 块 15.4 寸液晶显示器",[("count",6),("size","15.4 inch")]),
("esavn_fms","system","FMS","FMS,flight management system","集成导航性能优化和飞行计划管理的航电子系统",[]),
("esavn_weather_radar","system","气象雷达","weather radar,WXR","机载 X 波段气象雷达由 Collins 提供",[("supplier","Collins Aerospace")]),
("esavn_tcas","system","TCAS","TCAS,空中防撞系统","独立监视附近飞机并发出避撞建议的系统",[("version","TCAS II")]),
("esavn_egpws","system","EGPWS","EGPWS,enhanced GPWS","增强型地形感知和近地警告系统",[("supplier","Honeywell")]),
("esavn_adsb","system","ADS-B","ADS-B","飞机自动广播位置和状态信息的监视系统",[]),
("esavn_irs","system","惯导系统","IRS,inertial reference system","利用陀螺和加速度计测量姿态和位置的导航系统",[]),
("esavn_gps","system","GPS","GPS,global positioning system","卫星导航定位系统 C919 配备多模式接收机 MMR",[]),
("esavn_vhf","system","VHF 电台","VHF","甚高频空地话音和数据通信电台",[]),
("esavn_hf","system","HF 电台","HF","高频远程话音通信电台",[]),
("esavn_satcom","system","卫星通信","SATCOM","通过卫星实现的远程通信系统",[]),
("esavn_acars","system","ACARS","ACARS","空地数据链通信系统",[]),
("esavn_recorder","system","飞行记录仪","flight recorder,FDR/CVR","飞行数据记录器和驾驶舱话音记录器",[]),
("esavn_data_loader","system","数据加载机","data loader","航电数据库加载设备",[]),
])
# R0/T1-1：辅助系统实体块（esaux_ 前缀）为历史截断的陈旧块，其数据已被提交的
# entities-systems-auxiliary-20260728-candidate.yaml（saux_ 前缀，内容完整）取代。
# 为恢复 compileall 门禁，删除该截断的 ge(...) 调用；辅助系统数据请直接维护该 YAML。
